version: '2'

services:

  php-fpm:
    build:
      context: ./build/php-fpm
      dockerfile: Dockerfile-70
    container_name: php-fpm
    volumes_from:
      - application
    expose:
      - "9000"
    links:
      - mariadb

  application:
    build: ./build/application
    container_name: application
    volumes:
      - ./webroot:/var/www/codeigniter

  data:
    build: ./build/data
    container_name: data
    volumes:
#      - ./dbdata/mysql:/var/lib/mysql
      - ./dbdata/mariadb:/var/lib/mariadb
      - ./dbdata

  nginx:
    build: ./build/nginx
    container_name: nginx
    volumes_from:
      - application
    volumes:
      - ./logs/nginx/:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

#  mysql:
#    build: ./build/mysql
#    volumes_from:
#      - data
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: ci
#      MYSQL_USER: ci
#      MYSQL_PASSWORD: secret
#      MYSQL_ROOT_PASSWORD: root

  mariadb:
    build: ./build/mariadb
    container_name: mariadb
    volumes_from:
      - data
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ci
      MYSQL_USER: ci
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  redis:
    build: ./build/redis
    container_name: redis
    volumes_from:
      - data
    ports:
      - "6378:6379"

  workspace:
    build: ./build/workspace
    container_name: workspace
    volumes_from:
      - application
    tty: true
